# Generated by Django 4.2.1 on 2023-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=150)),
                ('Isbn', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
